function multiparticle(varargin)    
    control_loop('logname','part1','paths',[1,1,3.5,1,6,1], ...
        'draw',true,'ucb1_constant',0.001,'bandit_decay',0.999,'controller','bandit', ...        
        'save_images',true,varargin{:});
    control_loop('logname','part2','paths',[1,5,3.5,1,6,5], ...
        'draw',true,'ucb1_constant',0.001,'bandit_decay',0.999,'controller','bandit', ...        
        'save_images',true,varargin{:});    
    control_loop('logname','part3','paths',[1,3,1,1,1,5], ...
        'draw',true,'ucb1_constant',0.001,'bandit_decay',0.999,'controller','bandit', ...        
        'save_images',true,varargin{:});    
end