function rectangle(varargin)
    paths = [1,1;6,1;6,5;1,5;1,1];    
    control_loop('logname','rectangle','paths',paths, ...
        'draw',true,'maxsegment',0.1, ...
        'ucb1_constant',0.001,'bandit_decay',0.999,'controller','bandit', ...
        'bandit_variant','ucb1','save_images',true,...
        varargin{:});
end